config/routes.rb
Rails.application.routes.draw do
  root to: "top#top"
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "top/top" => "top#top"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title,presence: true
	validates :body,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  # GET /books
  # GET /books.json
  def index
    @book = Book.new
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])
  end

  # GET /books/1/edit
  def edit
     @book = Book.find(params[:id])
  end
  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
     @book = Book.find(params[:id])

  if @book.update(book_params)
     redirect_to book_path(@book.id), notice: 'Book was successfully updated.'
  else
     render :edit
  end
end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id), notice: 'Book was successfully created.'
    else
      @books = Book.all
      render :index
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: 'Book was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :body)
    end
end

app/controllers/home_controller.rb
class Controller < ApplicationController
  def top
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
	def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/books/_form.html.erb
<%= form_for book do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: "book_title" %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, class: "book_body" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> 

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<div>
  <%= render 'form', book: @book %>
</div>

<%= link_to 'Show', @book, class: "show_#{@book.id}" %> |
<%= link_to 'Back', books_path, class: "back" %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to 'Show', book_path(book.id), class: "show_#{book.id}" %></td>
        <td><%= link_to 'Edit', edit_book_path(book.id), class: "edit_#{book.id}" %></td>
        <td><%= link_to 'Destroy', book_path(book.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<h2>New book</h2>
<%= render 'form', book: @book %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @book.body %>
</p>

<%= link_to 'Edit', edit_book_path(@book.id), class: "edit_#{@book.id}" %> |
<%= link_to 'Back', books_path, class: "back" %>

app/views/home/top.html.erb
<h1>ようこそ <strong>Bookers</strong>  へ！</h1>
<p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p><p>印象を共有し交換することができます</p>
<p><%= link_to 'start' %></p>    	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebCampBackendNew</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/top.html.erb
<h1>ようこそ <strong>Bookers</strong>  へ！</h1>
<p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p><p>印象を共有し交換することができます</p>
<p><%= link_to 'start',books_path %></p>    	